package services

import (
	"context"
	"errors"
	"fmt"
	"log"
	"time"

	"github.com/automax/backend/internal/models"
	"github.com/automax/backend/internal/repository"
	"github.com/automax/backend/pkg/constants"
	"github.com/automax/backend/pkg/i18n"
	"github.com/automax/backend/pkg/utils"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

const feedbackTokenDuration = 72 * time.Hour

type IncidentPublicFeedbackService interface {
	Create(ctx context.Context, incidentID uuid.UUID, req *models.IncidentPublicFeedbackCreateRequest) (*models.IncidentPublicFeedbackResponse, error)
	// Init validates a 3-part incident signed token, creates or finds the pending feedback record,
	// and returns a valid fb-format signed token the frontend can pass to the Submit endpoint.
	Init(ctx context.Context, incidentID uuid.UUID, incidentToken string) (*models.IncidentPublicFeedbackInitResponse, error)
	Submit(ctx context.Context, incidentID uuid.UUID, feedbackID uuid.UUID, req *models.IncidentPublicFeedbackSubmitRequest) (*models.IncidentPublicFeedbackResponse, error)
	List(ctx context.Context) ([]models.IncidentPublicFeedbackResponse, error)
	ListByIncident(ctx context.Context, incidentID uuid.UUID) ([]models.IncidentPublicFeedbackResponse, error)
}

type incidentPublicFeedbackService struct {
	repo                   repository.IncidentPublicFeedbackRepository
	incidentRepo           repository.IncidentRepository
	notification           *NotificationService
	incidentService        IncidentService
	workflowRepo           repository.WorkflowRepository
	classificationRepo     repository.ClassificationRepository
	whatsappSessionCleanup *FinalCloseWhatsAppFeedbackSessionService
}

func NewIncidentPublicFeedbackService(
	repo repository.IncidentPublicFeedbackRepository,
	incidentRepo repository.IncidentRepository,
	notification *NotificationService,
	incidentService IncidentService,
	workflowRepo repository.WorkflowRepository,
	classificationRepo repository.ClassificationRepository,
	whatsappSessionCleanup *FinalCloseWhatsAppFeedbackSessionService,
) IncidentPublicFeedbackService {
	return &incidentPublicFeedbackService{
		repo:                   repo,
		incidentRepo:           incidentRepo,
		notification:           notification,
		incidentService:        incidentService,
		workflowRepo:           workflowRepo,
		classificationRepo:     classificationRepo,
		whatsappSessionCleanup: whatsappSessionCleanup,
	}
}

func (s *incidentPublicFeedbackService) Create(ctx context.Context, incidentID uuid.UUID, req *models.IncidentPublicFeedbackCreateRequest) (*models.IncidentPublicFeedbackResponse, error) {
	createdByID, ok := ctx.Value(constants.ContextKeys.UserID).(uuid.UUID)
	if !ok {
		return nil, errors.New(i18n.T(ctx, "user_context_missing"))
	}

	f := &models.IncidentPublicFeedback{
		IncidentID: incidentID,
		MobileNo:   req.MobileNo,
		Source:     req.Source,
		Meta:       req.Meta,
		ReporterID: req.ReporterID,
		CreatedBy:  createdByID,
	}

	if err := s.repo.Create(ctx, f); err != nil {
		return nil, fmt.Errorf("failed to create public feedback: %w", err)
	}

	token := utils.GenerateFeedbackToken(f.ID.String(), incidentID.String(), feedbackTokenDuration)

	// Send SMS asynchronously — a delivery failure must not block the API response.
	go func() {
		smsBody := req.Message
		if smsBody == "" {
			link := utils.BuildFeedbackLink(ctx, incidentID.String(), f.ID.String(), feedbackTokenDuration)
			smsBody = fmt.Sprintf("Please rate your experience. Submit your feedback here: %s", link)
		}
		if _, err := s.notification.SendNotification(
			context.Background(), "sms", nil, "en",
			[]string{f.MobileNo}, nil, nil,
			"", smsBody, nil, nil, &createdByID, nil,
		); err != nil {
			log.Printf("[IncidentPublicFeedback] SMS send failed for feedback %s: %v", f.ID, err)
		}
	}()

	resp := models.ToIncidentPublicFeedbackResponse(f)
	resp.SignedToken = token
	return &resp, nil
}

// Init validates the 3-part incident signed token (generated by GenerateIncidentToken and
// embedded in the {{feedback_url}} template variable), then returns or creates a pending
// feedback record together with a proper fb-format signed token for the Submit endpoint.
func (s *incidentPublicFeedbackService) Init(ctx context.Context, incidentID uuid.UUID, incidentToken string) (*models.IncidentPublicFeedbackInitResponse, error) {
	if err := utils.ValidateIncidentToken(incidentToken, incidentID.String()); err != nil {
		switch {
		case errors.Is(err, utils.ErrExpired):
			return nil, errors.New("token has expired")
		case errors.Is(err, utils.ErrIDMismatch):
			return nil, errors.New("token does not match this incident")
		default:
			return nil, errors.New("invalid token")
		}
	}

	// Reuse the latest unsubmitted feedback record if one exists, otherwise create a new one.
	f, err := s.repo.FindLatestPendingByIncidentID(ctx, incidentID)
	if err != nil {
		if !errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("failed to look up pending feedback: %w", err)
		}
		// No pending record — create one anonymously (no mobile number, web source).
		f = &models.IncidentPublicFeedback{
			IncidentID: incidentID,
			Source:     "web",
		}
		if err := s.repo.Create(ctx, f); err != nil {
			return nil, fmt.Errorf("failed to create feedback record: %w", err)
		}
	}

	token := utils.GenerateFeedbackToken(f.ID.String(), incidentID.String(), feedbackTokenDuration)
	return &models.IncidentPublicFeedbackInitResponse{
		FeedbackID:  f.ID,
		SignedToken: token,
	}, nil
}

func (s *incidentPublicFeedbackService) Submit(ctx context.Context, incidentID uuid.UUID, feedbackID uuid.UUID, req *models.IncidentPublicFeedbackSubmitRequest) (*models.IncidentPublicFeedbackResponse, error) {
	f, err := s.repo.FindByID(ctx, feedbackID)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errors.New("feedback record not found")
		}
		return nil, fmt.Errorf("failed to find feedback: %w", err)
	}

	if f.IncidentID != incidentID {
		return nil, errors.New("feedback does not belong to this incident")
	}

	if f.SubmittedAt != nil {
		return nil, errors.New("feedback has already been submitted")
	}

	// Block if another public feedback record for this incident was already submitted.
	otherPublic, err := s.repo.HasSubmittedFeedbackExcluding(ctx, incidentID, feedbackID)
	if err != nil {
		return nil, fmt.Errorf("failed to validate feedback status: %w", err)
	}
	if otherPublic {
		return nil, errors.New("Feedback has already been submitted for this incident")
	}

	// Block if a WhatsApp chatbot feedback (transition_history_id IS NULL) was already
	// written to incident_feedbacks for this incident.
	if s.incidentRepo != nil {
		whatsappDone, err := s.incidentRepo.HasWhatsAppFeedback(ctx, incidentID)
		if err != nil {
			return nil, fmt.Errorf("failed to validate feedback status: %w", err)
		}
		if whatsappDone {
			return nil, errors.New("Feedback has already been submitted for this incident via WhatsApp")
		}
	}

	now := time.Now()
	f.Satisfied = &req.Satisfied
	if req.Comment != "" {
		f.Comment = &req.Comment
	}
	f.SubmittedAt = &now
	f.UpdatedAt = now

	if err := s.repo.Update(ctx, f); err != nil {
		return nil, fmt.Errorf("failed to submit feedback: %w", err)
	}

	// Feedback was just submitted via this channel (typically the SMS fallback
	// link) — a WhatsApp feedback session for the same reporter may still be
	// active. Delete it so that link stops working. Best-effort: log and move
	// on, never fail the submission because of this cleanup step.
	if s.whatsappSessionCleanup != nil && f.MobileNo != "" {
		mobileNo := f.MobileNo
		feedbackID := f.ID
		go func() {
			cleanupCtx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
			defer cancel()
			if cleanupErr := s.whatsappSessionCleanup.DeleteSession(cleanupCtx, mobileNo); cleanupErr != nil {
				log.Printf("[IncidentPublicFeedback] WhatsApp session cleanup failed for feedback %s (mobile=%s): %v", feedbackID, mobileNo, cleanupErr)
			} else {
				log.Printf("[IncidentPublicFeedback] WhatsApp session cleanup completed for feedback %s (mobile=%s)", feedbackID, mobileNo)
			}
		}()
	}

	resp := models.ToIncidentPublicFeedbackResponse(f)

	// Not satisfied → create a complaint synchronously and include its number in the response.
	if !req.Satisfied {
		complaintNumber, complaintID, complaintErr := s.createComplaint(ctx, f)
		if complaintErr != nil {
			log.Printf("[IncidentPublicFeedback] complaint creation failed for feedback %s: %v", f.ID, complaintErr)
			resp.ComplaintError = complaintErr.Error()
		} else {
			resp.ComplaintNumber = complaintNumber
			if complaintID != uuid.Nil {
				resp.ComplaintID = &complaintID
				f.ComplaintID = &complaintID
				if updateErr := s.repo.Update(ctx, f); updateErr != nil {
					log.Printf("[IncidentPublicFeedback] failed to persist complaint_id on feedback %s: %v", f.ID, updateErr)
				}
			}
		}
	}

	return &resp, nil
}

// createComplaint resolves the first active complaint workflow and classification,
// creates a complaint record, and returns its incident number, ID, and any error.
func (s *incidentPublicFeedbackService) createComplaint(ctx context.Context, f *models.IncidentPublicFeedback) (string, uuid.UUID, error) {
	workflows, err := s.workflowRepo.ListByRecordType(ctx, "complaint", true)
	if err != nil {
		return "", uuid.Nil, fmt.Errorf("failed to query complaint workflows: %w", err)
	}
	if len(workflows) == 0 {
		return "", uuid.Nil, fmt.Errorf("no active complaint workflow found — create one in workflow settings")
	}
	workflow := workflows[0]

	classifications, err := s.classificationRepo.ListByType(ctx, []string{"complaint"})
	if err != nil {
		return "", uuid.Nil, fmt.Errorf("failed to query complaint classifications: %w", err)
	}
	// Filter to only active classifications.
	var activeClassifications []models.Classification
	for _, c := range classifications {
		if c.IsActive {
			activeClassifications = append(activeClassifications, c)
		}
	}
	if len(activeClassifications) == 0 {
		return "", uuid.Nil, fmt.Errorf("no active complaint classification found — create one in classification settings")
	}
	classification := activeClassifications[0]

	comment := ""
	if f.Comment != nil {
		comment = *f.Comment
	}
	reporterID := f.CreatedBy.String()
	sourceIncidentID := f.IncidentID.String()

	complaintReq := &models.CreateComplaintRequest{
		Title:            fmt.Sprintf("Unsatisfied feedback for incident %s", f.IncidentID),
		Description:      comment,
		ClassificationID: classification.ID.String(),
		WorkflowID:       workflow.ID.String(),
		SourceIncidentID: &sourceIncidentID,
		ReporterID:       &reporterID,
		Source:           f.Source,
		Channel:          f.Source,
	}

	complaint, err := s.incidentService.CreateComplaint(ctx, complaintReq, f.CreatedBy)
	if err != nil {
		return "", uuid.Nil, fmt.Errorf("CreateComplaint failed: %w", err)
	}
	return complaint.IncidentNumber, complaint.ID, nil
}

func (s *incidentPublicFeedbackService) List(ctx context.Context) ([]models.IncidentPublicFeedbackResponse, error) {
	items, err := s.repo.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list public feedback: %w", err)
	}
	return models.ToIncidentPublicFeedbackResponseList(items), nil
}

func (s *incidentPublicFeedbackService) ListByIncident(ctx context.Context, incidentID uuid.UUID) ([]models.IncidentPublicFeedbackResponse, error) {
	items, err := s.repo.FindByIncidentID(ctx, incidentID)
	if err != nil {
		return nil, fmt.Errorf("failed to list public feedback for incident: %w", err)
	}
	return models.ToIncidentPublicFeedbackResponseList(items), nil
}
